CREATE TABLE usuarios(
id INTEGER PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(70) NOT NULL,
cpf VARCHAR(11) NOT NULL,
dt_nascimento DATE,
email VARCHAR(100) NOT NULL,
senha VARCHAR(25) NOT NULL,
telefone VARCHAR(11) NOT NULL
);